"""add production feedbacks

Revision ID: f81a78f8c1c4
Revises: 98ff29894521
Create Date: 2026-07-27 19:17:27.807105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f81a78f8c1c4'
down_revision: Union[str, Sequence[str], None] = '98ff29894521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_result_id', sa.Integer(), nullable=False),
    sa.Column('criterion_description', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('guidance', sa.Text(), nullable=False),
    sa.Column('generator_id', sa.String(), nullable=False),
    sa.Column('generator_version', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_result_id'], ['production_evaluation_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_feedbacks_evaluation_result_id'), 'production_feedbacks', ['evaluation_result_id'], unique=False)
    op.create_index(op.f('ix_production_feedbacks_id'), 'production_feedbacks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_feedbacks_id'), table_name='production_feedbacks')
    op.drop_index(op.f('ix_production_feedbacks_evaluation_result_id'), table_name='production_feedbacks')
    op.drop_table('production_feedbacks')
    # ### end Alembic commands ###
